# Generated by Django 5.2.7 on 2025-10-13 15:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='budget_period_valid',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='period_start',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Optional month number (1–12) for monthly budget. Leave empty for default budget.', null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'account', 'month'), name='unique_budget_per_month'),
        ),
    ]
