# Generated by Django 5.2.7 on 2025-10-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_budget_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['category', 'month']},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='account',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text="Optional month number (1–12). If not set, it's the default budget.", null=True),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month'), name='unique_budget_per_category_month'),
        ),
    ]
