# Generated by Django 5.2.7 on 2025-10-13 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_budget_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_month',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category')},
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
    ]
